### ISSUE TITLE
DELETE on schedules endpoint 404's

### ISSUE THREAD

**Issue by imsickofmaps** [praekelt/mama-ng-scheduler#40]
To replicate: GET http://mama-ng-scheduler.qa.praekelt.com/mama-ng-scheduler/rest/schedules/11 responds with body, then DELETE responds with a 404 `"/WEB-INF/grails-app/views/error.gsp" not found.` This might be a template missing issue, masking a bug.

**Comment by imsickofmaps** [comment]
@hodgestar can I check if this is tracked on a backlog anywhere?

**Comment by hodgestar** [comment]
@imsickofmaps It's on our current sprint board under the mole-whacking card.

**Comment by hodgestar** [comment]
Duplicate of #36.
